# Jekyll! config for blog
# YAML cheet sheet  https://learntheweb.courses/topics/markdown-yaml-cheat-sheet/#yaml

# settings for blog
title: Web Programming Basics
description: "Sep 2023"
owner_name: Hayden Chen
github_username: monke7769
baseurl: "/haydenwebprogbasics"
future: true

# theme requirements
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

